name: pubspec
version: 2.1.0
homepage: https://github.com/j4qfrost/pubspec
description: A library for manipulating [pubspec](https://www.dartlang.org/tools/pub/pubspec.html) files
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  path: ^1.8.0
  pub_semver: ^2.0.0
  yaml: ^3.1.0
  uri: ^1.0.0
dev_dependencies:
  test: ^1.16.8
